# https://squidfunk.github.io/mkdocs-material/getting-started/
# https://www.mkdocs.org/user-guide/writing-your-docs/
site_name: Mo's Mods 2 Wiki
docs_dir: pages
repo_url: https://github.com/mosharky/Mos-Mods-2
repo_name: mosharky/Mos-Mods-2
nav:
  - 🏠Home: 'index.md'
  - 📋Information & Guides:
    - Installation: 'information_and_guides/installation.md'
    - Performance: 'information_and_guides/performance.md'
    - Additional Tips: 'information_and_guides/additional_tips.md'
    - Modlist: 'information_and_guides/modlist.md'
  - 📜Changelogs:
    - v2.2.0: 'changelogs/v2.2.0.md'
    - v2.2.1: 'changelogs/v2.2.1.md'
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys # keybind thingy
  - tables
  - toc:
      permalink: true
theme:
  name: material
  logo: https://raw.githubusercontent.com/mosharky/Mos-Mods-2/main/.github/docs/assets/logo.png
  favicon: https://raw.githubusercontent.com/mosharky/Mos-Mods-2/main/.github/docs/assets/logo.ico
  highlightjs: true
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.path
    # - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
