name = "Mo's Mons' SMP"
author = "mosharky"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d046ff10edbfe78319d4b764f44f920623c0b09ddfd82d17ec9007bd9ecb1e5"

[versions]
forge = "47.2.8"
minecraft = "1.20.1"
