name = "Mo's Mods 2"
author = "mosharky"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "742276140497027ad8aabe8747c03246a0e62f6ca6e74636846a587a0c98cbfa"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
