name = "Mo's Mods 2"
author = "mosharky"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c736f6fe5ea3145281ae8a99c558c7b693225b02ad4cb2829f16fcf7f97b007b"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
