name = "Mo's Mods 2"
author = "mosharky"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa7c0287eca9abfaf39ec7dc6c1bd1145dc1a00c4c0e9ea33f863e8ba5687527"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
