name = "Mo's Mons' SMP"
author = "mosharky"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e57a7e806adc8ee059ca5f9490299d45d2be8e2c258732cb13e9849437deea5"

[versions]
forge = "47.2.8"
minecraft = "1.20.1"
