name = "Mo's Mods 2"
author = "mosharky"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0494a9d69172a9663397714198c5b8bafd404ae5c81c9c016d7589c84b6ccc06"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
