name = "Mo's Mods 2"
author = "mosharky"
version = "2.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "874e23a430e6a9246c7c99bc98b6829b06512cff7003112a905f5be9039e85bd"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
