name = "Mo's Mods 2"
author = "mosharky"
version = "2.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1907358bf036933540930df84bede9911daeaed9b0a9d293bc5d2687cd6e863"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
