name = "Mo's Mods 2"
author = "mosharky"
version = "2.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edfcda55f4eb8aafd60f7bf64589cecca7da3eb68544945677322d74b664e256"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
