name = "Mo's Mods 2"
author = "mosharky"
version = "2.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d90f3ef8981e5f9958b634f9411a2e8c1318d53c29947c6f98608eb55b95f399"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
