name = "Mo's Mods 2"
author = "mosharky"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b99e96e0a75a6074b5c75f211e9ec72487d502d2bad61fef20f04fa33eb4763e"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
