name = "Mo's Mods 2"
author = "mosharky"
version = "2.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49371275883ba1d001bb8ef9cd40706ad0823241f701a52f9d99bbceac97793a"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
