name = "Mo's Mods 2"
author = "mosharky"
version = "2.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "510c7c63747dfc7f9fbbadf98d095fcb5f3bb406be534127a394e3459e4c7e2a"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"
