//priority: 10

// ⚠️ ITEMS ⚠️
ServerEvents.tags('item', e => {
    e.add('forge:cheeses/normal', 'brewinandchewin:flaxen_cheese_wedge')
    e.add('forge:cheeses/nether', 'brewinandchewin:scarlet_cheese_wedge')
    e.add('forge:storage_blocks/cheese', 'brewinandchewin:flaxen_cheese_wheel')
    e.add('forge:storage_blocks/nether_cheese', 'brewinandchewin:scarlet_cheese_wheel')
    e.add('curios:body', /aether:.*cape.*/)
    e.add('forge:plates', [
        'createdeco:zinc_sheet',
    ])
    e.add('forge:plates/zinc', 'createdeco:zinc_sheet',)
    e.add('kubejs:raw_lobster', [
        'alexsmobs:lobster_tail',
        'crabbersdelight:clawster'
    ])
    e.add('kubejs:raw_crab', [
        'crabbersdelight:crab',
        'quark:crab_leg'
    ])
    e.add('crabbersdelight:raw_seafood', [
        'alexsmobs:lobster_tail',
        'quark:crab_leg',
        'alexscaves:mussel',
    ])
    e.add('crabbersdelight:cooked_seafood', [
        'alexsmobs:cooked_lobster_tail',
        'quark:cooked_crab_leg',
        'alexscaves:cooked_mussel',
    ])

    e.add('createbigcannons:block_cast_iron', 'create:industrial_iron_block')
    e.add('createbigcannons:nugget_cast_iron', 'createdeco:industrial_iron_nugget')
    e.add('createbigcannons:ingot_cast_iron', 'createdeco:industrial_iron_ingot')

    e.remove('c:iron_ingots', 'betternether:cincinnasite_ingot')
    e.add('forge:ores/redstone', 'betternether:nether_redstone_ore')

    e.add('forge:boxes/shulker', global.ironShulkerBoxes)
    e.add('minecraft:shulker_boxes', global.ironShulkerBoxes)

    // origins
    let caveDwarfFoods = [
        'galosphere:lichen_cordyceps',
        'galosphere:golden_lichen_cordyceps',
        'galosphere:salted_jerky',
        'galosphere:preserved_flesh',
    ]
    Ingredient.of('@miners_delight').itemIds.forEach(item => {
        if (Item.of(item).isEdible()) caveDwarfFoods.push(item)
    })
    e.add('kubejs:cave_dwarf_foods', caveDwarfFoods)
    e.add('kubejs:cave_dwarf_hammers', [
        'embers:tinker_hammer',
        'embers:grandhammer',
        'iceandfire:troll_weapon_hammer',
        'mutantmonsters:hulk_hammer',
        'aether:hammer_of_kingbdogz'
    ])
    e.add('kubejs:precious_equipment', [
        /minecraft:golden_(helmet|chestplate|leggings|boots|axe|sword|pickaxe|shovel|hoe)/,
        /minecraft:netherite_(helmet|chestplate|leggings|boots|axe|sword|pickaxe|shovel|hoe)/,
        /eidolon:silver_(helmet|chestplate|leggings|boots|axe|sword|pickaxe|shovel|hoe)/,
        /eidolon:bonelord_(helm|chestplate|greaves)/,
        /botania:(manasteel|terrasteel|elementium)_(helmet|chestplate|leggings|boots|axe|sword|pickaxe|shovel|hoe)/,
        /embers:ashen_(goggles|cloak|leggings|boots)/,
        /embers:dawnstone_(axe|sword|pickaxe|shovel|hoe)/,
        /embers:clockwork_(axe|grandhammer|pickaxe)/,
        /create:netherite_diving_(helmet|backtank|boots)/,
        'alexscaves:diving_leggings',
        /iceandfire:dragonsteel_.*_(helmet|chestplate|leggings|boots|axe|sword|pickaxe|shovel|hoe)/,
        /rats:ratlantis_(helmet|chestplate|leggings|boots|axe|sword|pickaxe|shovel|hoe)/,
        /cataclysm:ignitium_(helmet|.*chestplate|leggings|boots)/,
        /aether:(valkyrie|gravitite)_(helmet|chestplate|leggings|boots|lance|axe|sword|pickaxe|shovel|hoe)/,
        /cataclysm:(bulwark_of_the_flame|the_incinerator|gauntlet_of_guard|gauntlent_of_bulwark|meat_shredder|void_forge|tidal_claws|infernal_forge|monstrous_helm)/,
    ])

    // meats
    e.add('kubejs:meat', [
        '#alexscaves:raw_meats',
        '#crabbersdelight:cooked_seafood',
        '#crabbersdelight:raw_seafood',
        '#forge:cooked_fishes',
        '#forge:raw_fishes',
        '#minecraft:fishes',
        '#origins:meat',
        'aether_redux:mouse_ear_soup',
        'alexscaves:cooked_lanternfish',
        'alexscaves:cooked_mussel',
        'alexscaves:cooked_radgill',
        'alexscaves:cooked_trilocaris_tail',
        'alexscaves:cooked_tripodfish',
        'alexscaves:deep_sea_sushi_roll',
        'alexscaves:dinosaur_nugget',
        'alexscaves:lanternfish',
        'alexscaves:mussel',
        'alexscaves:primordial_soup',
        'alexscaves:radgill',
        'alexscaves:sea_pig',
        'alexscaves:seething_stew',
        'alexscaves:slam',
        'alexscaves:stinky_fish',
        'alexscaves:trilocaris_tail',
        'alexscaves:tripodfish',
        'alexscaves:vesper_stew',
        'alexscaves:vesper_wing',
        'alexsmobs:blobfish',
        'alexsmobs:cooked_catfish',
        'alexsmobs:cooked_kangaroo_meat',
        'alexsmobs:cooked_moose_ribs',
        'alexsmobs:cosmic_cod',
        'alexsmobs:flying_fish',
        'alexsmobs:kangaroo_burger',
        'alexsmobs:kangaroo_meat',
        'alexsmobs:maggot',
        'alexsmobs:moose_ribs',
        'alexsmobs:rainbow_jelly',
        'alexsmobs:raw_catfish',
        'alexsmobs:shrimp_fried_rice',
        'alexsmobs:sopa_de_macaco',
        'ancient_aether:buffalo_rib',
        'ancient_aether:buffalo_ribs',
        'ancient_aether:cooked_buffalo_ribs',
        'aquamirae:cooked_spinefish',
        'aquamirae:esca',
        'aquamirae:fin',
        'aquamirae:poseidons_breakfast',
        'aquamirae:sea_casserole',
        'aquamirae:sea_stew',
        'aquamirae:sharp_bones',
        'aquamirae:spinefish',
        'betterend:end_fish_cooked',
        'betterend:end_fish_raw',
        'brewinandchewin:ham_and_cheese_sandwich',
        'brewinandchewin:kippers',
        'brewinandchewin:supreme_pizza_slice',
        'cataclysm:amethyst_crab_meat',
        'cataclysm:blessed_amethyst_crab_meat',
        'cataclysm:lionfish',
        'crabbersdelight:bisque',
        'crabbersdelight:clam_bake',
        'crabbersdelight:clam_chowder',
        'crabbersdelight:clawster',
        'crabbersdelight:cooked_clam_meat',
        'crabbersdelight:cooked_clawster',
        'crabbersdelight:cooked_crab',
        'crabbersdelight:cooked_shrimp',
        'crabbersdelight:cooked_tropical_fish_slice',
        'crabbersdelight:cooked_tropical_fish',
        'crabbersdelight:crab_cakes',
        'crabbersdelight:crab_legs',
        'crabbersdelight:crab',
        'crabbersdelight:fish_stick',
        'crabbersdelight:raw_clam_meat',
        'crabbersdelight:seafood_gumbo',
        'crabbersdelight:shrimp_skewer',
        'crabbersdelight:shrimp',
        'crabbersdelight:stuffed_nautilus_shell',
        'crabbersdelight:surf_and_turf',
        'crabbersdelight:tropical_fish_slice',
        'create:sweet_roll',
        'deep_aether:cooked_aerglow_fish',
        'deep_aether:cooked_quail',
        'deep_aether:raw_aerglow_fish',
        'deep_aether:raw_quail',
        'eidolon:withered_heart',
        'eidolon:zombie_heart',
        'endersdelight:crawling_sandwich',
        'endersdelight:crispy_skewer',
        'endersdelight:ender_paella_wood',
        'endersdelight:ender_paella',
        'endersdelight:endermite_stew_wood',
        'endersdelight:endermite_stew',
        'endersdelight:mite_crust',
        'endersdelight:pearl_pasta_wood',
        'endersdelight:pearl_pasta',
        'endersdelight:shulker_filet',
        'endersdelight:shulker_mollusk',
        'endersdelight:strange_eclair',
        'endersdelight:stuffed_shulker_bowl',
        'endersdelight:twisted_cereal_wood',
        'endersdelight:twisted_cereal',
        'endersdelight:uncanny_cookies',
        'enlightened_end:cooked_stalker',
        'enlightened_end:raw_stalker',
        'enlightened_end:squished_bouncer',
        'farmersdelight:bacon_and_eggs',
        'farmersdelight:bacon_sandwich',
        'farmersdelight:bacon',
        'farmersdelight:baked_cod_stew',
        'farmersdelight:barbecue_stick',
        'farmersdelight:beef_patty',
        'farmersdelight:beef_stew',
        'farmersdelight:bone_broth',
        'farmersdelight:chicken_cuts',
        'farmersdelight:chicken_sandwich',
        'farmersdelight:chicken_soup',
        'farmersdelight:cod_roll',
        'farmersdelight:cod_slice',
        'farmersdelight:cooked_bacon',
        'farmersdelight:cooked_chicken_cuts',
        'farmersdelight:cooked_cod_slice',
        'farmersdelight:cooked_mutton_chops',
        'farmersdelight:cooked_salmon_slice',
        'farmersdelight:dog_food',
        'farmersdelight:fish_stew',
        'farmersdelight:grilled_salmon',
        'farmersdelight:ham',
        'farmersdelight:hamburger',
        'farmersdelight:honey_glazed_ham',
        'farmersdelight:minced_beef',
        'farmersdelight:mutton_chops',
        'farmersdelight:mutton_wrap',
        'farmersdelight:noodle_soup',
        'farmersdelight:pasta_with_meatballs',
        'farmersdelight:pasta_with_mutton_chop',
        'farmersdelight:pumpkin_soup',
        'farmersdelight:ratatouille',
        'farmersdelight:roast_chicken',
        'farmersdelight:roasted_mutton_chops',
        'farmersdelight:salmon_roll',
        'farmersdelight:salmon_slice',
        'farmersdelight:shepherds_pie',
        'farmersdelight:smoked_ham',
        'farmersdelight:squid_ink_pasta',
        'farmersdelight:steak_and_potatoes',
        'galosphere:preserved_flesh',
        'galosphere:salted_jerky',
        'goated:chevon',
        'goated:cooked_chevon',
        'hauntedharvest:succotash',
        'iceandfire:fire_dragon_flesh',
        'iceandfire:ice_dragon_flesh',
        'iceandfire:lightning_dragon_flesh',
        'letfishlove:cod_roe',
        'letfishlove:pufferfish_roe',
        'letfishlove:salmon_roe',
        'letfishlove:tropical_fish_roe',
        'minecraft:beef',
        'minecraft:chicken',
        'minecraft:cod',
        'minecraft:cooked_beef',
        'minecraft:cooked_chicken',
        'minecraft:cooked_cod',
        'minecraft:cooked_mutton',
        'minecraft:cooked_porkchop',
        'minecraft:cooked_rabbit',
        'minecraft:cooked_salmon',
        'minecraft:mutton',
        'minecraft:porkchop',
        'minecraft:pufferfish',
        'minecraft:rabbit_stew',
        'minecraft:rabbit',
        'minecraft:rotten_flesh',
        'minecraft:salmon',
        'minecraft:spider_eye',
        'minecraft:tropical_fish',
        'miners_delight:arthropod',
        'miners_delight:baked_cod_stew_cup',
        'miners_delight:baked_squid',
        'miners_delight:baked_tentacles',
        'miners_delight:bat_cookie',
        'miners_delight:bat_rolls',
        'miners_delight:bat_soup_cup',
        'miners_delight:bat_soup',
        'miners_delight:bat_wing',
        'miners_delight:beef_stew_cup',
        'miners_delight:bone_broth_cup',
        'miners_delight:bowl_of_stuffed_squid',
        'miners_delight:chicken_soup_cup',
        'miners_delight:cooked_arthropod',
        'miners_delight:fish_stew_cup',
        'miners_delight:glow_ink_pasta',
        'miners_delight:glow_squid',
        'miners_delight:improvised_barbecue_stick',
        'miners_delight:insect_sandwich',
        'miners_delight:insect_stew_cup',
        'miners_delight:insect_stew',
        'miners_delight:insect_wrap',
        'miners_delight:noodle_soup_cup',
        'miners_delight:pumpkin_soup_cup',
        'miners_delight:rabbit_stew_cup',
        'miners_delight:seasoned_arthropods',
        'miners_delight:smoked_bat_wing',
        'miners_delight:squid_sandwich',
        'miners_delight:squid',
        'miners_delight:takoyaki',
        'miners_delight:tentacles',
        'nethersdelight:grilled_strider',
        'nethersdelight:ground_strider',
        'nethersdelight:hoglin_ear',
        'nethersdelight:hoglin_loin',
        'nethersdelight:hoglin_sirloin',
        'nethersdelight:nether_skewer',
        'nethersdelight:plate_of_stuffed_hoglin_ham',
        'nethersdelight:plate_of_stuffed_hoglin_roast',
        'nethersdelight:plate_of_stuffed_hoglin_snout',
        'nethersdelight:strider_moss_stew',
        'nethersdelight:strider_slice',
        'nethersdelight:warped_moldy_meat',
        'rats:cooked_rat',
        'rats:potato_knishes',
        'rats:rat_burger',
        'rats:ratfish',
        'rats:raw_rat',
        'farmersdelight:dumplings',
    ])

    // vegetarian
    e.add('kubejs:vegetarian', [
        'aether_redux:blue_swet_jelly',
        'aether_redux:blueberry_pie',
        'aether_redux:chromaberry',
        'aether_redux:enchanted_blueberry_pie',
        'aether_redux:glowbuds',
        'aether_redux:golden_swet_jelly',
        'aether_redux:lightroot_clump',
        'aether_redux:lightroot_clump',
        'aether_redux:luxbuds',
        'aether_redux:oat_muffin',
        'aether_redux:oats',
        'aether_redux:purified_glowbuds',
        'aether_redux:purified_luxbuds',
        'aether_redux:quickroot',
        'aether_redux:sweetblossom',
        'aether_redux:vanilla_gummy_swet',
        'aether_redux:vanilla_swet_jelly',
        'aether:blue_berry',
        'aether:blue_gummy_swet',
        'aether:candy_cane',
        'aether:enchanted_berry',
        'aether:gingerbread_man',
        'aether:golden_gummy_swet',
        'aether:white_apple',
        'alexscaves:darkened_apple',
        'alexscaves:green_soylent',
        'alexscaves:pine_nuts',
        'alexscaves:serene_salad',
        'alexscaves:spelunkie',
        'alexsmobs:banana',
        'alexsmobs:boiled_emu_egg',
        'alexsmobs:gongylidia',
        'alexsmobs:mosquito_repellent_stew',
        'ancient_aether:grapes',
        'betterend:amber_root_raw',
        'betterend:blossom_berry_jelly',
        'betterend:blossom_berry',
        'betterend:bolux_mushroom_cooked',
        'betterend:cave_pumpkin_pie',
        'betterend:chorus_mushroom_cooked',
        'betterend:chorus_mushroom_raw',
        'betterend:shadow_berry_cooked',
        'betterend:shadow_berry_jelly',
        'betterend:shadow_berry_raw',
        'betterend:sweet_berry_jelly',
        'betterend:umbrella_cluster_juice',
        'betternether:agave_medicine',
        'betternether:black_apple',
        'betternether:herbal_medicine',
        'betternether:hook_mushroom_cooked',
        'betternether:stalagnate_bowl_apple',
        'betternether:stalagnate_bowl_mushroom',
        'betternether:stalagnate_bowl_wart',
        'brewinandchewin:cheese_pizza_slice',
        'brewinandchewin:cheesy_pasta',
        'brewinandchewin:cocoa_fudge',
        'brewinandchewin:creamy_onion_soup',
        'brewinandchewin:flaxen_cheese_wedge',
        'brewinandchewin:kimchi',
        'brewinandchewin:mead',
        'brewinandchewin:pickled_pickles',
        'brewinandchewin:saccharine_rum',
        'brewinandchewin:scarlet_cheese_wedge',
        'brewinandchewin:scarlet_pierogies',
        'brewinandchewin:vegetable_omelet',
        'crabbersdelight:kelp_shake',
        'create:chocolate_glazed_berries',
        'create:honeyed_apple',
        'deep_aether:blue_squash_slice',
        'deep_aether:goldenleaf_berries',
        'deep_aether:green_squash_slice',
        'deep_aether:purple_squash_slice',
        'domesticationinnovation:rotten_apple',
        'domesticationinnovation:sinister_carrot',
        'eidolon:fungus_sprouts',
        'eidolon:grape_candy',
        'eidolon:red_candy',
        'eidolon:warped_sprouts',
        'endersdelight:chorus_juice',
        'endersdelight:chorus_pie_slice',
        'endersdelight:chorus_stew_wood',
        'endersdelight:chorus_stew',
        'enlightened_end:ancient_root',
        'enlightened_end:azure_berries',
        'enlightened_end:bubble_jelly_bottle',
        'enlightened_end:chorus_soup',
        'enlightened_end:elevibloom',
        'enlightened_end:frost_fruit',
        'enlightened_end:glow_gourd_slice',
        'farmersdelight:apple_cider',
        'farmersdelight:apple_pie_slice',
        'farmersdelight:cabbage_leaf',
        'farmersdelight:cabbage_rolls',
        'farmersdelight:cabbage',
        'farmersdelight:cake_slice',
        'farmersdelight:chocolate_pie_slice',
        'farmersdelight:cooked_rice',
        'farmersdelight:egg_sandwich',
        'farmersdelight:fried_egg',
        'farmersdelight:fried_rice',
        'farmersdelight:fruit_salad',
        'farmersdelight:glow_berry_custard',
        'farmersdelight:honey_cookie',
        'farmersdelight:kelp_roll_slice',
        'farmersdelight:kelp_roll',
        'farmersdelight:melon_popsicle',
        'farmersdelight:mixed_salad',
        'farmersdelight:mushroom_rice',
        'farmersdelight:nether_salad',
        'farmersdelight:onion',
        'farmersdelight:pie_crust',
        'farmersdelight:pumpkin_slice',
        'farmersdelight:raw_pasta',
        'farmersdelight:stuffed_potato',
        'farmersdelight:stuffed_pumpkin',
        'farmersdelight:sweet_berry_cheesecake_slice',
        'farmersdelight:sweet_berry_cookie',
        'farmersdelight:tomato_sauce',
        'farmersdelight:tomato',
        'farmersdelight:vegetable_noodles',
        'farmersdelight:vegetable_soup',
        'farmersdelight:wheat_dough',
        'galosphere:golden_lichen_cordyceps',
        'galosphere:lichen_cordyceps',
        'hauntedharvest:candy_corn',
        'hauntedharvest:corn_on_the_cob',
        'hauntedharvest:cornbread',
        'hauntedharvest:grim_apple',
        'hauntedharvest:popcorn',
        'hauntedharvest:rotten_apple',
        'kawaiidishes:beijinho',
        'kawaiidishes:brigadeiro',
        'kawaiidishes:coffee_fruit',
        'kawaiidishes:cookie_of_unbinding',
        'kiwiboi:kiwicake',
        'minecraft:apple',
        'minecraft:baked_potato',
        'minecraft:beetroot_soup',
        'minecraft:beetroot',
        'minecraft:bread',
        'minecraft:cake',
        'minecraft:carrot',
        'minecraft:chorus_fruit',
        'minecraft:cookie',
        'minecraft:dried_kelp',
        'minecraft:glow_berries',
        'minecraft:golden_carrot',
        'minecraft:melon_slice',
        'minecraft:mushroom_stew',
        'minecraft:poisonous_potato',
        'minecraft:potato',
        'minecraft:pumpkin_pie',
        'minecraft:sweet_berries',
        'miners_delight:baked_cave_carrot',
        'miners_delight:beetroot_soup_cup',
        'miners_delight:cave_carrot',
        'miners_delight:cave_soup_cup',
        'miners_delight:cave_soup',
        'miners_delight:copper_carrot',
        'miners_delight:moss',
        'miners_delight:mushroom_stew_cup',
        'miners_delight:pasta_with_veggieballs',
        'miners_delight:silverfish_eggs',
        'miners_delight:vegan_hamburger',
        'miners_delight:vegan_patty',
        'miners_delight:vegan_steak_and_potatoes',
        'miners_delight:vegan_wrap',
        'miners_delight:vegetable_soup_cup',
        'miners_delight:weird_caviar',
        'nethersdelight:magma_gelatin',
        'nethersdelight:propelpearl',
        'quark:ancient_fruit',
        'rats:assorted_vegetables',
        'rats:blue_cheese',
        'rats:herb_bundle',
        'rats:plague_stew',
        'rats:potato_pancake',
        'rats:string_cheese',
        'rats:treacle',
        'regions_unexplored:duskmelon_slice',
        'regions_unexplored:hanging_earlight_fruit',
        'regions_unexplored:meadow_sage',
        'regions_unexplored:salmonberry',
        'snowyspirit:candy_cane',
        'snowyspirit:eggnog',
        'snowyspirit:gingerbread_cookie',
        'supplementaries:candy',
        'supplementaries:pancake',
        'twilightforest:experiment_115',
        'twilightforest:maze_wafer',
    ])

    // stuff that ignores vegetarian vs carnivore
    e.add('origins:ignore_diet', [
        'aether:healing_stone',
        'alexsmobs:fish_oil',
        'aquamirae:sweet_lance',
        'botania:mana_bottle',
        'botania:mana_cookie',
        'brewinandchewin:beer',
        'brewinandchewin:bloody_mary',
        'brewinandchewin:dread_nog',
        'brewinandchewin:egg_grog',
        'brewinandchewin:glittering_grenadine',
        'brewinandchewin:mead',
        'brewinandchewin:pale_jane',
        'brewinandchewin:red_rum',
        'brewinandchewin:rice_wine',
        'brewinandchewin:saccharine_rum',
        'brewinandchewin:salty_folly',
        'brewinandchewin:steel_toe_stout',
        'brewinandchewin:strongroot_ale',
        'brewinandchewin:vodka',
        'brewinandchewin:withering_dross',
        'create:bar_of_chocolate',
        'create:builders_tea',
        'iceandfire:ambrosia',
        'iceandfire:pixie_dust',
        'iwannaskate:energy_drink',
        'minecraft:enchanted_golden_apple',
        'minecraft:golden_apple',
        'minecraft:honey_bottle',
        'minecraft:suspicious_stew',
        'obscure_api:vial_of_knowledge',
        'supplementaries:soap',
    ])

    // debug carnivore/vegetarian fix
    // Ingredient.of(/.*/).itemIds.forEach(item => {
    //     if (Item.of(item).isEdible() && !Item.of(item).hasTag('kubejs:vegetarian') && !Item.of(item).hasTag('kubejs:meat') && !Item.of(item).hasTag('origins:ignore_diet')) {
    //         console.log(item)
    //     }
    // })
})


// ⚠️ BLOCKS ⚠️
ServerEvents.tags('block', e => {
    // fixing frozen grass being placed on top of snowrealmagic:snow
    e.remove('regions_unexplored:snow_plant_can_survive_on', '#minecraft:snow')
    e.add('regions_unexplored:snow_plant_can_survive_on', [
        'minecraft:snow',
        'minecraft:snow_block'
    ])

    e.add('snowrealmagic:containables', [
        '#regions_unexplored:grass',
    ])

    e.add('forge:boxes/shulker', global.ironShulkerBoxes)
    e.add('minecraft:shulker_boxes', global.ironShulkerBoxes)
})

ServerEvents.tags('fluid', e => {
    e.removeAllTagsFrom('embers:molten_bronze')
    e.removeAllTagsFrom('cofh_core:honey')
    e.add('forge:molten_zinc', 'kubejs:molten_zinc')
    e.add('forge:molten_brass', 'kubejs:molten_brass')
    e.add('embers:ingot_tooltip', [
        'kubejs:molten_zinc',
        'kubejs:molten_brass',
        'createbigcannons:molten_bronze'
    ])
})


// ⚠️ ENTITIES ⚠️
ServerEvents.tags('entity_type', e => {
    e.add('forge:bosses', [
        'cataclysm:amethyst_crab',
        'cataclysm:ancient_remnant',
        'cataclysm:ender_guardian',
        'cataclysm:ignis',
        'cataclysm:netherite_monstrosity',
        'cataclysm:the_harbinger',
        'cataclysm:the_leviathan',
        'cataclysm:the_prowler',
        'cataclysm:the_watcher',
        'iceandfire:fire_dragon',
        'iceandfire:ice_dragon',
        'iceandfire:lightning_dragon',
        'iceandfire:gorgon',
        'iceandfire:cyclops',
        'iceandfire:siren',
        'iceandfire:death_worm',
        'iceandfire:troll',
        'iceandfire:myrmex_queen',
        'iceandfire:hydra',
        'conjurer_illager:conjurer',
        /mutantmonsters:mutant_(creeper|enderman|skeleton|zombie)/
    ])
    e.add('ad_astra:can_survive_extreme_cold', '#forge:bosses')
    e.add('ad_astra:can_survive_in_space', '#forge:bosses')
    e.add('aether:no_skyroot_double_drops', '#forge:bosses')
    e.add('alexsmobs:ignores_kimono', '#forge:bosses')
    e.add('alexsmobs:sunbird_scorch_targets', '#forge:bosses')
    e.add('botania:shaded_mesa_blacklist', '#forge:bosses')
    e.add('cataclysm:ignis_cant_poke', '#forge:bosses')
    e.add('domesticationinnovation:infamy_target_attracked', '#forge:bosses')
    e.add('endermanoverhaul:cant_be_teleported', '#forge:bosses')
    e.add('minecraft:fall_damage_immune', '#forge:bosses')
    e.add('minecraft:freeze_immune_entity_types', '#forge:bosses')

    e.add('numismatic-overhaul:the_bourgeoisie', [
        '#minecraft:raiders',
        'quark:forgotten',
    ])

    e.removeAll('supplementaries:cage_catchable')
    e.add('supplementaries:cage_catchable', [
        'minecraft:allay',
        'minecraft:axolotl',
        'minecraft:bat',
        'minecraft:bee',
        'minecraft:camel',
        'minecraft:cat',
        'minecraft:chicken',
        'minecraft:cow',
        'minecraft:dolphin',
        'minecraft:donkey',
        'minecraft:enderman',
        'minecraft:endermite',
        'minecraft:fox',
        'minecraft:frog',
        'minecraft:glow_squid',
        'minecraft:goat',
        'minecraft:horse',
        'minecraft:iron_golem',
        'minecraft:llama',
        'minecraft:magma_cube',
        'minecraft:mooshroom',
        'minecraft:mule',
        'minecraft:ocelot',
        'minecraft:panda',
        'minecraft:parrot',
        'minecraft:pig',
        'minecraft:polar_bear',
        'minecraft:rabbit',
        'minecraft:sheep',
        'minecraft:silverfish',
        'minecraft:skeleton_horse',
        'minecraft:slime',
        'minecraft:sniffer',
        'minecraft:snow_golem',
        'minecraft:squid',
        'minecraft:strider',
        'minecraft:trader_llama',
        'minecraft:turtle',
        'minecraft:vex',
        'minecraft:wolf',
        'minecraft:zombie_horse',
        'ad_astra:glacian_ram',
        'alexsmobs:grizzly_bear',
        'alexsmobs:roadrunner',
        'alexsmobs:gazelle',
        'alexsmobs:crocodile',
        'alexsmobs:fly',
        'alexsmobs:hummingbird',
        'alexsmobs:orca',
        'alexsmobs:sunbird',
        'alexsmobs:gorilla',
        'alexsmobs:rattlesnake',
        'alexsmobs:endergrade',
        'alexsmobs:hammerhead_shark',
        'alexsmobs:lobster',
        'alexsmobs:komodo_dragon',
        'alexsmobs:capuchin_monkey',
        'alexsmobs:warped_toad',
        'alexsmobs:moose',
        'alexsmobs:raccoon',
        'alexsmobs:blobfish',
        'alexsmobs:seal',
        'alexsmobs:cockroach',
        'alexsmobs:shoebill',
        'alexsmobs:elephant',
        'alexsmobs:snow_leopard',
        'alexsmobs:crow',
        'alexsmobs:alligator_snapping_turtle',
        'alexsmobs:mungus',
        'alexsmobs:mantis_shrimp',
        'alexsmobs:emu',
        'alexsmobs:platypus',
        'alexsmobs:tasmanian_devil',
        'alexsmobs:kangaroo',
        'alexsmobs:bald_eagle',
        'alexsmobs:tiger',
        'alexsmobs:tarantula_hawk',
        'alexsmobs:seagull',
        'alexsmobs:toucan',
        'alexsmobs:maned_wolf',
        'alexsmobs:anaconda',
        'alexsmobs:anteater',
        'alexsmobs:rocky_roller',
        'alexsmobs:flutter',
        'alexsmobs:gelada_monkey',
        'alexsmobs:jerboa',
        'alexsmobs:terrapin',
        'alexsmobs:comb_jelly',
        'alexsmobs:bunfungus',
        'alexsmobs:bison',
        'alexsmobs:giant_squid',
        'alexsmobs:skelewag',
        'alexsmobs:rain_frog',
        'alexsmobs:potoo',
        'alexsmobs:mudskipper',
        'alexsmobs:rhinoceros',
        'alexsmobs:sugar_glider',
        'alexsmobs:farseer',
        'alexsmobs:skunk',
        'alexsmobs:banana_slug',
        'alexsmobs:blue_jay',
        'alexsmobs:caiman',
        'alexsmobs:triops',
        'alexsmobs:cosmaw',
        'alexsmobs:laviathan',
        'alexsmobs:mimicube',
        'alexsmobs:sea_bear',
        'alexsmobs:stradpole',
        'alexsmobs:tusklin',
        'alexscaves:ferrouslime',
        'alexscaves:gammaroach',
        'alexscaves:gloomoth',
        'alexscaves:notor',
        'alexscaves:radgill',
        'alexscaves:raycat',
        'aquamirae:luminous_jelly',
        'aquamirae:golden_moth',
        'aqupdcaracal:caracal',
        'betterend:cubozoa',
        'betterend:dragonfly',
        'betterend:end_slime',
        'betterend:silk_moth',
        'betternether:firefly',
        'betternether:skull',
        'cataclysm:endermaptera',
        'corpse:corpse',
        'creeperoverhaul:mushroom_creeper',
        'endermanoverhaul:badlands_enderman',
        'endermanoverhaul:cave_enderman',
        'endermanoverhaul:crimson_forest_enderman',
        'endermanoverhaul:dark_oak_enderman',
        'endermanoverhaul:desert_enderman',
        'endermanoverhaul:end_enderman',
        'endermanoverhaul:end_islands_enderman',
        'endermanoverhaul:flower_fields_enderman',
        'endermanoverhaul:ice_spikes_enderman',
        'endermanoverhaul:mushroom_fields_enderman',
        'endermanoverhaul:nether_wastes_enderman',
        'endermanoverhaul:ocean_enderman',
        'endermanoverhaul:savanna_enderman',
        'endermanoverhaul:snowy_enderman',
        'endermanoverhaul:soulsand_valley_enderman',
        'endermanoverhaul:swamp_enderman',
        'endermanoverhaul:warped_forest_enderman',
        'endermanoverhaul:windswept_hills_enderman',
        'endermanoverhaul:scarab',
        'endermanoverhaul:spirit',
        'fennecfox:fennecfox',
        'aether:aerbunny',
        'aether:blue_swet',
        'aether:flying_cow',
        'aether:golden_swet',
        'aether:mimic',
        'aether:moa',
        'aether:phyg',
        'aether:sheepuff',
        'aether:sentry',
        'aether_redux:vanilla_swet',
        'eidolon:raven',
        'eidolon:slimy_slug',
        'galosphere:spectre',
        'galosphere:sparkle',
        'galosphere:specterpillar',
        'goated:geep',
        'kiwiboi:kiwi',
        'rats:demon_rat',
        'rats:dutchrat',
        'rats:feral_ratlantean',
        'rats:ghost_pirat',
        'rats:neo_ratlantean',
        'rats:pied_piper',
        'rats:pirat',
        'rats:rat',
        'rats:ratfish',
        'rats:tamed_rat',
        'railways:conductor',
        'quark:crab',
        'quark:shiba'
    ])
})