
[waila]

	#You can disable specific modules in the WAILA config.
	[waila.pokemon]
		#Valid TooltipTypes: TITLE, TITLE_GENDER, SPECIES, LEVEL, GENDER, HEALTH, TRAINER, NICKNAME, FRIENDSHIP, TYPES, REWARD_EVS, NATURE, ABILITY, IVS, EVS, DEX_ENTRY, SNEAK_HINT, BATTLE_HINT
		pokemonTooltips = ["TITLE_GENDER:SHOW", "HEALTH:SHOW", "TRAINER:SHOW", "TYPES:SHOW", "REWARD_EVS:SHOW", "SNEAK_HINT:NO_SNEAK", "FRIENDSHIP:SNEAK", "NATURE:SNEAK", "ABILITY:SNEAK", "IVS:SNEAK", "EVS:SNEAK", "DEX_ENTRY:SNEAK", "BATTLE_HINT:SNEAK"]

	[waila.misc]
		#Hide the Pokemon label/nametag completely.
		hidePokemonLabel = true

[enhancedcelestials]
	#Use datapacks for LunarEvent configuration.
	#Apply EXP/EV changes only in wild battles?
	applyInPVP = false
	#Allow Pokemon to spawn/evolve using the lunarEvent conditions? (setting to False will disable all lunar event variants)
	allowLunarEventVariants = true

