
[highlight]
	enabled = true
	#Distance at which the player highlight will take effect
	#Range: 0 ~ 10000
	distance = 20
	#Highlight color
	color = "#FFE630BF"
	#Range: 0 ~ 10000
	duration = 100

